import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from 'next/font/google'
import Header from "@/components/layout/header/Header";
import Footer from "@/components/layout/footer";
const montserrat = Montserrat({
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal'],
  subsets: ['cyrillic', 'latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat}`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
